version: '3.7'
services:
  redis:
    image: redislabs/rejson:latest
    restart: unless-stopped
    command: redis-server --loadmodule "/usr/lib/redis/modules/rejson.so" --requirepass "$REDIS_PASSWORD"
    ports:
        - 13000:6379
  app:
    build:
      context: .
      target: base
    ports:
      - 5000:5000
    environment:
     - ENV=local
    volumes: 
     - .:/app
    depends_on:
      - redis
    env_file: 
      - local_conf/app.conf

  locust_master:
    build:
      context: .
      target: test
    ports:
     - "8089:8089"
    environment:
     - ENV=local
    volumes:
      - .:/test
    entrypoint: locust --web-host=0.0.0.0 --host=http://app:5000 --master --tags addSimpleJSON
    env_file: 
      - local_conf/locust.conf
    depends_on:
      - app
  
  locust_worker:
    build:
      context: .
      target: test
    environment:
    - ENV=local
    volumes:
      - .:/test
    entrypoint: locust --worker --master-host locust_master
    env_file: 
      - local_conf/locust.conf
    depends_on:
      - app

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
        - 8080:8080
    privileged: true
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
        - app


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
        - 9090:9090
    command:
        - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro


  grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - ./grafana.ini:/etc/grafana/grafana.ini
            - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
        depends_on:
            - prometheus
