{
 "title": "Locust for Prometheus",
 "description": "all locust infos in one page",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Reqeusts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(locust_stats_current_rps) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_num_requests) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_num_failures) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_avg_response_time) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_max_response_time) by (method, path)"
    }
   ]
  },
  {
   "title": "Transations per sec(Total)",
   "type": "graph",
   "description": "tps",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_current_rps{path=\"Aggregated\"}",
     "legendFormat": "Req/s"
    },
    {
     "expr": "locust_stats_current_fail_per_sec{path=\"Aggregated\"}",
     "legendFormat": "Failure/s"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "locust_stats_num_requests{path=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Response_time(ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_avg_response_time{path=\"Aggregated\"}",
     "legendFormat": "avg_response_time(total)"
    },
    {
     "expr": "locust_stats_median_response_time{path=\"Aggregated\"}",
     "legendFormat": "response_time(median)"
    },
    {
     "expr": "locust_stats_ninetieth_response_time{path=\"Aggregated\"}",
     "legendFormat": "response_time(90%)"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "locust_stats_num_failures{path=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Slave runners",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "locust_slave_count" }
   ]
  },
  {
   "title": "Failed rate %",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "targets": [
    { "expr": "locust_fail_ratio * 100" }
   ]
  },
  {
   "title": "Num of users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "locust_user_count" }
   ]
  },
  {
   "title": "Transations per sec",
   "type": "graph",
   "description": "tps",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_current_rps{path!=\"Aggregated\"}",
     "legendFormat": "{{method}}-{{path}}"
    }
   ]
  },
  {
   "title": "Avg_content_length(Total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_avg_content_length{path=\"Aggregated\"}",
     "legendFormat": "avg_content_length"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "description": "tps",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, path, error)"
    }
   ]
  }
 ]
}