scrape_configs:
- job_name: locust
  scrape_interval: 5s
  static_configs:
  - targets:
    - locust_master:8089
- job_name: prometheus_scrapper
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080