{
 "title": "Locust for Prometheus Copy",
 "description": "all locust infos in one page",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reqeusts",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(locust_stats_current_rps) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_num_requests) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_num_failures) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_avg_response_time) by (method, path)"
    },
    {
     "expr": "sum(locust_stats_max_response_time) by (method, path)"
    }
   ]
  },
  {
   "title": "Median response_time per service",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_median_response_time{path!=\"Aggregated\"}",
     "legendFormat": "{{method}}-{{path}}"
    }
   ]
  },
  {
   "title": "Transations RPS per service",
   "type": "graph",
   "description": "tps",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_current_rps{path!=\"Aggregated\"}",
     "legendFormat": "{{method}}-{{path}}"
    }
   ]
  },
  {
   "title": "Size of Request Per service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_avg_content_length{path!=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "locust_stats_num_requests{path=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Response_time(ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_avg_response_time{path=\"Aggregated\"}",
     "legendFormat": "avg_response_time(total)"
    },
    {
     "expr": "locust_stats_median_response_time{path=\"Aggregated\"}",
     "legendFormat": "response_time(median)"
    },
    {
     "expr": "locust_stats_ninetieth_response_time{path=\"Aggregated\"}",
     "legendFormat": "response_time(90%)"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 21 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "locust_stats_num_failures{path=\"Aggregated\"}"
    }
   ]
  },
  {
   "title": "Failed rate %",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "locust_fail_ratio * 100" }
   ]
  },
  {
   "title": "Slave runners",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "locust_slave_count" }
   ]
  },
  {
   "title": "# Of Requests Per Service",
   "type": "graph",
   "description": "tps",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_stats_num_requests{path!=\"Aggregated\"}",
     "legendFormat": "Req/s"
    }
   ]
  },
  {
   "title": "Num of users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "locust_user_count" }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "description": "tps",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, path, error)"
    }
   ]
  }
 ]
}